server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: betelgeuse-core
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/orion_core}
    username: ${SPRING_DATASOURCE_USERNAME:orion}
    password: ${SPRING_DATASOURCE_PASSWORD:orion}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html
